version: '3.8'

services:
  zookeeper:
    build: 
      context: .
      dockerfile: Dockerfile-zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      - KAFKA_USER_HOME=/usr/local/kafka
    volumes:
      - ./:/usr/local/kafka
    restart: always

  kafka:
    build: 
      context: .
      dockerfile: Dockerfile-kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_USER_HOME=/usr/local/kafka
    volumes:
      - ./:/usr/local/kafka
    depends_on:
      - zookeeper
    restart: always
