# Dockerfile-kafka
# Basado en la imagen oficial de Python
FROM python:3.10.12-slim-bullseye

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Actualizar e instalar dependencias del sistema
RUN apt-get update -y \
  && apt-get upgrade -y \
  && apt-get install -y --no-install-recommends \
    ufw net-tools bleachbit wget git gdebi curl \
    build-essential gdb lcov pkg-config libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev \
    libncurses5-dev libreadline6-dev libsqlite3-dev libssl-dev lzma lzma-dev tk-dev uuid-dev zlib1g-dev \
    libpq-dev lsof

# Install OpenJDK
RUN apt-get install -y openjdk-11-jdk

# Limpiar el caché de apt
RUN apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Define las variables
ARG KAFKA_USER_HOME=/usr/local/kafka
ENV KAFKA_HOME=${KAFKA_USER_HOME}

# Establece el directorio de trabajo
WORKDIR ${KAFKA_HOME}

# Install dependencies
COPY requirements.txt ${KAFKA_HOME}
RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY kafka_2.13-3.5.0 ${KAFKA_HOME}

EXPOSE 9092

CMD ["bin/kafka-server-start.sh", "config/server.properties"]
